fix(ci): update verify deployment

diff --git a/.github/workflows/create-cicd.yaml b/.github/workflows/create-cicd.yaml
--- a/.github/workflows/create-cicd.yaml
+++ b/.github/workflows/create-cicd.yaml
@@ -76,4 +76,8 @@ jobs:
             --output text)
           
           echo "Stack deployment status: $STACK_STATUS"
+          if [[ "$STACK_STATUS" != "CREATE_COMPLETE" && "$STACK_STATUS" != "UPDATE_COMPLETE" ]]; then
+            echo "CloudFormation stack deployment failed with status: $STACK_STATUS"
+            exit 1
+          fi
 
